name: Deploy to Freebox

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH with password
        uses: appleboy/ssh-action@master
        with:
          host: mon-suivis-sportif.freeboxos.fr
          username: freebox
          password: ${{ secrets.SSH_PASSWORD }}
          port: 49154
          script: |
            cd /var/www/mon-suivi-sportif
            git pull origin master
            echo "✅ Déploiement réussi !"